<?php
namespace strong\components;

use yii\base\Component;

class EasySms extends Component
{
    public $config;

    public $easySms;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->easySms = new \Overtrue\EasySms\EasySms($this->config);
    }
}